version: '3.1'

services:
  leonidas-postgresql:
    container_name: LEONIDAS_POSTGRESQL
    image: postgres:latest
    ports:
    - 5432:5432/tcp
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: inventory
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
